    setMode(IONIAN);
    intro(instrument, octave );
    verse(instrument, octave );
    chorus(instrument, octave );
    verse(instrument, octave );
    chorus(instrument, octave );
    bridge(instrument, octave );
    verse(instrument, octave );
    chorus(instrument, octave );
    outro(instrument, octave );
